package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.VerticalScrollArrangement;
import com.google.appinventor.components.runtime.VerticalArrangement;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.Canvas;
import com.google.appinventor.components.runtime.Ball;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.CheckBox;
import com.google.appinventor.components.runtime.TimePicker;
import com.google.appinventor.components.runtime.Slider;
import com.google.appinventor.components.runtime.Notifier;
import com.google.appinventor.components.runtime.FirebaseDB;
import com.google.appinventor.components.runtime.Sound;
class Screen1 extends Form implements HandlesEventDispatching {
  private VerticalScrollArrangement VerticalScrollArrangement1;
  private VerticalArrangement VerticalArrangement4;
  private HorizontalArrangement HorizontalArrangement7;
  private Label LabelActualValue;
  private TextBox TextBoxActualValue;
  private Label Label8;
  private HorizontalArrangement AlarmBox;
  private Label Label12;
  private Canvas Canvas1;
  private Ball Alarm;
  private TableArrangement TableArrangement1;
  private Button Button1;
  private VerticalArrangement VerticalArrangement3;
  private HorizontalArrangement HorizontalArrangement9;
  private CheckBox CheckDimi;
  private HorizontalArrangement HorizontalArrangement1;
  private TimePicker DeLaDimi;
  private TextBox Dimi1;
  private HorizontalArrangement HorizontalArrangement4;
  private TimePicker PanaLaDimi;
  private TextBox Dimi2;
  private Label Label4;
  private HorizontalArrangement HorizontalArrangement12;
  private TextBox DimiMax;
  private Label Label10;
  private Slider SliderDimi;
  private TableArrangement TableArrangement2;
  private Button Button2;
  private VerticalArrangement VerticalArrangement2;
  private HorizontalArrangement HorizontalArrangement10;
  private CheckBox CheckPranz;
  private HorizontalArrangement HorizontalArrangement2;
  private TimePicker DeLaPranz;
  private TextBox Pranz1;
  private HorizontalArrangement HorizontalArrangement5;
  private TimePicker PanaLaPranz;
  private TextBox Pranz2;
  private Label Label5;
  private HorizontalArrangement HorizontalArrangement8;
  private TextBox PranzMax;
  private Label Label9;
  private Slider SliderPranz;
  private TableArrangement TableArrangement4;
  private Button Button4;
  private VerticalArrangement VerticalArrangement1;
  private HorizontalArrangement HorizontalArrangement11;
  private CheckBox CheckSeara;
  private HorizontalArrangement HorizontalArrangement14;
  private TimePicker DeLaSeara;
  private TextBox Seara1;
  private HorizontalArrangement HorizontalArrangement3;
  private TimePicker PanaLaSeara;
  private TextBox Seara2;
  private CheckBox nextDay;
  private Label Label6;
  private HorizontalArrangement HorizontalArrangement13;
  private TextBox SearaMax;
  private Label Label11;
  private Slider SliderSeara;
  private TableArrangement TableArrangement3;
  private Button Button3;
  private Notifier Notifier1;
  private FirebaseDB FirebaseDB1;
  private Sound Sound1;
  protected void $define() {
    this.AppName("Noise Monitor");
    this.Icon("Icon.jpg");
    this.Title("Noise Monitor");
    VerticalScrollArrangement1 = new VerticalScrollArrangement(this);
    VerticalScrollArrangement1.Width(LENGTH_FILL_PARENT);
    VerticalArrangement4 = new VerticalArrangement(VerticalScrollArrangement1);
    VerticalArrangement4.AlignHorizontal(3);
    VerticalArrangement4.AlignVertical(2);
    VerticalArrangement4.Height(-1010);
    VerticalArrangement4.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement7 = new HorizontalArrangement(VerticalArrangement4);
    HorizontalArrangement7.AlignHorizontal(3);
    HorizontalArrangement7.AlignVertical(2);
    LabelActualValue = new Label(HorizontalArrangement7);
    LabelActualValue.Text("Valoare actuală");
    TextBoxActualValue = new TextBox(HorizontalArrangement7);
    TextBoxActualValue.FontBold(true);
    TextBoxActualValue.Width(-1020);
    TextBoxActualValue.Hint("Hint for TextBox1");
    TextBoxActualValue.NumbersOnly(true);
    TextBoxActualValue.Text("52");
    Label8 = new Label(HorizontalArrangement7);
    Label8.Text("db");
    AlarmBox = new HorizontalArrangement(VerticalArrangement4);
    AlarmBox.AlignHorizontal(3);
    AlarmBox.AlignVertical(2);
    AlarmBox.Height(LENGTH_FILL_PARENT);
    AlarmBox.Visible(false);
    Label12 = new Label(AlarmBox);
    Label12.Text("Nivel maxim depășit!");
    Canvas1 = new Canvas(AlarmBox);
    Canvas1.BackgroundColor(0x00FFFFFF);
    Canvas1.Height(-1005);
    Canvas1.Width(-1010);
    Canvas1.LineWidth(0);
    Canvas1.PaintColor(0x00FFFFFF);
    Alarm = new Ball(Canvas1);
    Alarm.Initialize();
    Alarm.PaintColor(0xFFFF0000);
    Alarm.Radius(10);
    Alarm.X(2);
    Alarm.Y(7);
    Alarm.Z(0);
    TableArrangement1 = new TableArrangement(VerticalScrollArrangement1);
    Button1 = new Button(TableArrangement1);
    Button1.BackgroundColor(0x00FFFFFF);
    Button1.Column(1);
    Button1.Enabled(false);
    Button1.Row(0);
    VerticalArrangement3 = new VerticalArrangement(VerticalScrollArrangement1);
    VerticalArrangement3.AlignHorizontal(3);
    VerticalArrangement3.AlignVertical(2);
    VerticalArrangement3.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement9 = new HorizontalArrangement(VerticalArrangement3);
    HorizontalArrangement9.AlignHorizontal(3);
    HorizontalArrangement9.AlignVertical(2);
    HorizontalArrangement9.BackgroundColor(0x00FFFFFF);
    CheckDimi = new CheckBox(HorizontalArrangement9);
    CheckDimi.Text("Dimineața");
    HorizontalArrangement1 = new HorizontalArrangement(VerticalArrangement3);
    HorizontalArrangement1.AlignVertical(2);
    DeLaDimi = new TimePicker(HorizontalArrangement1);
    DeLaDimi.BackgroundColor(0xAC1DFFB6);
    DeLaDimi.FontBold(true);
    DeLaDimi.Text("De la");
    DeLaDimi.TextColor(0xFF000000);
    Dimi1 = new TextBox(HorizontalArrangement1);
    HorizontalArrangement4 = new HorizontalArrangement(VerticalArrangement3);
    HorizontalArrangement4.AlignVertical(2);
    PanaLaDimi = new TimePicker(HorizontalArrangement4);
    PanaLaDimi.BackgroundColor(0xFF1DFFB6);
    PanaLaDimi.Enabled(false);
    PanaLaDimi.FontBold(true);
    PanaLaDimi.Text("Până la");
    Dimi2 = new TextBox(HorizontalArrangement4);
    Label4 = new Label(VerticalArrangement3);
    Label4.Text("Valoare maximă");
    HorizontalArrangement12 = new HorizontalArrangement(VerticalArrangement3);
    HorizontalArrangement12.AlignVertical(2);
    DimiMax = new TextBox(HorizontalArrangement12);
    DimiMax.Width(-1020);
    DimiMax.NumbersOnly(true);
    DimiMax.Text("80");
    Label10 = new Label(HorizontalArrangement12);
    Label10.Text("db");
    SliderDimi = new Slider(VerticalArrangement3);
    SliderDimi.ColorLeft(0xFF1DFFB6);
    SliderDimi.Width(-1090);
    SliderDimi.MaxValue(100);
    SliderDimi.MinValue(20);
    SliderDimi.ThumbPosition(80);
    TableArrangement2 = new TableArrangement(VerticalArrangement3);
    Button2 = new Button(TableArrangement2);
    Button2.BackgroundColor(0x00FFFFFF);
    Button2.Column(1);
    Button2.Enabled(false);
    Button2.Row(0);
    VerticalArrangement2 = new VerticalArrangement(VerticalScrollArrangement1);
    VerticalArrangement2.AlignHorizontal(3);
    VerticalArrangement2.BackgroundColor(0x00FFFFFF);
    VerticalArrangement2.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement10 = new HorizontalArrangement(VerticalArrangement2);
    HorizontalArrangement10.AlignHorizontal(3);
    HorizontalArrangement10.AlignVertical(2);
    CheckPranz = new CheckBox(HorizontalArrangement10);
    CheckPranz.Text("Prânz");
    HorizontalArrangement2 = new HorizontalArrangement(VerticalArrangement2);
    HorizontalArrangement2.AlignHorizontal(3);
    HorizontalArrangement2.AlignVertical(2);
    DeLaPranz = new TimePicker(HorizontalArrangement2);
    DeLaPranz.BackgroundColor(0x423848FF);
    DeLaPranz.FontBold(true);
    DeLaPranz.Text("De la");
    DeLaPranz.TextColor(0xFF000000);
    Pranz1 = new TextBox(HorizontalArrangement2);
    HorizontalArrangement5 = new HorizontalArrangement(VerticalArrangement2);
    HorizontalArrangement5.AlignHorizontal(3);
    HorizontalArrangement5.AlignVertical(2);
    PanaLaPranz = new TimePicker(HorizontalArrangement5);
    PanaLaPranz.BackgroundColor(0x733848FF);
    PanaLaPranz.Enabled(false);
    PanaLaPranz.FontBold(true);
    PanaLaPranz.Text("Până la");
    PanaLaPranz.TextColor(0xFF000000);
    Pranz2 = new TextBox(HorizontalArrangement5);
    Label5 = new Label(VerticalArrangement2);
    Label5.Text("Valoare maximă");
    HorizontalArrangement8 = new HorizontalArrangement(VerticalArrangement2);
    HorizontalArrangement8.AlignHorizontal(3);
    HorizontalArrangement8.AlignVertical(2);
    PranzMax = new TextBox(HorizontalArrangement8);
    PranzMax.Width(-1020);
    PranzMax.NumbersOnly(true);
    PranzMax.Text("40");
    Label9 = new Label(HorizontalArrangement8);
    Label9.Text("db");
    SliderPranz = new Slider(VerticalArrangement2);
    SliderPranz.ColorLeft(0x423848FF);
    SliderPranz.Width(-1090);
    SliderPranz.MaxValue(100);
    SliderPranz.MinValue(20);
    SliderPranz.ThumbPosition(40);
    TableArrangement4 = new TableArrangement(VerticalArrangement2);
    Button4 = new Button(TableArrangement4);
    Button4.BackgroundColor(0x00FFFFFF);
    Button4.Column(1);
    Button4.Enabled(false);
    Button4.Row(0);
    VerticalArrangement1 = new VerticalArrangement(VerticalScrollArrangement1);
    VerticalArrangement1.AlignHorizontal(3);
    VerticalArrangement1.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement11 = new HorizontalArrangement(VerticalArrangement1);
    HorizontalArrangement11.AlignHorizontal(3);
    HorizontalArrangement11.AlignVertical(2);
    CheckSeara = new CheckBox(HorizontalArrangement11);
    CheckSeara.Text("Seara");
    HorizontalArrangement14 = new HorizontalArrangement(VerticalArrangement1);
    HorizontalArrangement14.AlignVertical(2);
    DeLaSeara = new TimePicker(HorizontalArrangement14);
    DeLaSeara.BackgroundColor(0x5E0042FF);
    DeLaSeara.FontBold(true);
    DeLaSeara.Text("De la");
    Seara1 = new TextBox(HorizontalArrangement14);
    HorizontalArrangement3 = new HorizontalArrangement(VerticalArrangement1);
    HorizontalArrangement3.AlignVertical(2);
    PanaLaSeara = new TimePicker(HorizontalArrangement3);
    PanaLaSeara.BackgroundColor(0x7F0042FF);
    PanaLaSeara.Enabled(false);
    PanaLaSeara.FontBold(true);
    PanaLaSeara.Text("Până la");
    Seara2 = new TextBox(HorizontalArrangement3);
    nextDay = new CheckBox(VerticalArrangement1);
    nextDay.Text("A doua zi?");
    Label6 = new Label(VerticalArrangement1);
    Label6.Text("Valoare maximă");
    HorizontalArrangement13 = new HorizontalArrangement(VerticalArrangement1);
    HorizontalArrangement13.AlignVertical(2);
    SearaMax = new TextBox(HorizontalArrangement13);
    SearaMax.Width(-1020);
    SearaMax.NumbersOnly(true);
    SearaMax.Text("25");
    Label11 = new Label(HorizontalArrangement13);
    Label11.Text("db");
    SliderSeara = new Slider(VerticalArrangement1);
    SliderSeara.ColorLeft(0xFF0000FF);
    SliderSeara.Width(-1090);
    SliderSeara.MaxValue(100);
    SliderSeara.MinValue(20);
    SliderSeara.ThumbPosition(25);
    TableArrangement3 = new TableArrangement(VerticalScrollArrangement1);
    Button3 = new Button(TableArrangement3);
    Button3.BackgroundColor(0x00FFFFFF);
    Button3.Column(1);
    Button3.Enabled(false);
    Button3.Row(0);
    Notifier1 = new Notifier(this);
    FirebaseDB1 = new FirebaseDB(this);
    //FirebaseDB1.FirebaseToken(eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkIjp7InVpZCI6Ijc0YjI5ZjZjLTk3MGItNDIyZi1hMTJiLTNlMDUzMjQ1MDliNiIsInByb2plY3QiOiIiLCJkZXZlbG9wZXIiOiJhbmRyZWljdXNpYWNAZ21haWw6Y29tIn0sInYiOjAsImV4cCI6MTY3MzQxMTg5NzcsImlhdCI6MTY4MTQyNDU3N30.mtYbjk_cpNccRJtCnzlMhHTX8dJcGV0xNUAM7_Y2Z3U);
    //FirebaseDB1.FirebaseURL(https://noise-monitor-d2b64-default-rtdb.firebaseio.com/);
    //FirebaseDB1.ProjectBucket(Noise_monitor);
    Sound1 = new Sound(this);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}